### ISSUE TITLE
CheXGCN is a method in paper，but i can't found information about that

### ISSUE THREAD

**Issue by wyh196646** [Nkechinyere-Agu/AnaXnet-Original#1]
CheXGCN is a method in paper，but i can't found information about that，what is that

**Comment by Nkechinyere-Agu** [comment]
The CheXGCN is a model from the paper "Label Co-Occurrence Learning With Graph Convolutional Networks for Multi-Label Chest X-Ray Image Classification". The paper can be found here https://ieeexplore.ieee.org/document/8961143

**Comment by wyh196646** [comment]
> 
really thanks

**Comment by axz520** [comment]
In AnaXnetGCN findings_gcn's input "findings_inp" may be the 300*14 vector created by label embeddings. Could you share the label embeddings? Thanks!!!
